In [ ]:
import sklearn.preprocessing as pp
from sklearn.feature_extraction import DictVectorizer

v =  DictVectorizer(sparse=False)
D = [{'foo': 'Banana', 'bar': 2}, {'foo': 'Apple', 'bar': 1}, {'foo': 'Apple', 'bar': 1} ]
print(v.fit_transform(D))

v.get_feature_names()



[[ 2.  0.  1.]
 [ 1.  1.  0.]
 [ 1.  1.  0.]]


['bar', 'foo=Apple', 'foo=Banana']

In [280]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import Imputer
import numpy as np

def write_result(result):
    with open('result.csv', 'w+') as f:
        f.write("PassengerId,Survived\n")
        for row in result:
            f.write(" %d,%d\n" % row)

classifier = LogisticRegression(C=1, 
                                penalty='l2', 
                                #solver='lbfgs',
                                tol=0.01)



imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
dropped_columns = ['PassengerId','Name','Ticket','Fare','Cabin','Embarked']

df_train = pd.read_csv("../titanic_data/train.csv")
df_test = pd.read_csv("../titanic_data/test.csv")


df_test_features = df_test.drop(dropped_columns,axis=1)
df_train_features = df_train.drop(dropped_columns + ["Survived"], axis=1)


df_train_survived = df_train.iloc[:,1]

df_train_features = pd.get_dummies(df_train_features)

df_test_features = pd.get_dummies(df_test_features)
df_test_idx = df_test.iloc[:,0]

df_train_features = imputer.fit_transform(df_train_features)
df_test_features = imputer.fit_transform(df_test_features)

classifier.fit(df_train_features, df_train_survived)

classifier.predict(df_test_features)
result_labels = classifier.predict(df_test_features)

ys = zip(df_test_idx,result_labels)

write_result(ys)


print('Done!')

Done!


In [284]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import Imputer
from sklearn.feature_extraction import DictVectorizer

import numpy as np


def write_result(result):
    with open('result.csv', 'w+') as f:
        f.write("PassengerId,Survived\n")
        for row in result:
            f.write(" %d,%d\n" % row)

classifier = LogisticRegression(C=1, 
                                penalty='l2', 
                                #solver='lbfgs',
                                tol=0.01)

vectorizer = DictVectorizer(sparse=False)

imputer = Imputer(missing_values='NaN', strategy='mean', axis=0)
dropped_columns = ['PassengerId',
                   'Name',
                   'Ticket',
                   'Fare',
                   #'Cabin',
                   'Embarked']

df_train = pd.read_csv("../titanic_data/train.csv")
df_test = pd.read_csv("../titanic_data/test.csv")


df_test_features = df_test.drop(dropped_columns,axis=1)
df_train_features = df_train.drop(dropped_columns + ["Survived"], axis=1)

dict_train_features = df_train_features.to_dict( orient = 'records' )


fit(X[, y])

# df_train_survived = df_train.iloc[:,1]

# df_train_features = pd.get_dummies(df_train_features)

# df_test_features = pd.get_dummies(df_test_features)
# df_test_idx = df_test.iloc[:,0]

# df_train_features = imputer.fit_transform(df_train_features)
# df_test_features = imputer.fit_transform(df_test_features)

# classifier.fit(df_train_features, df_train_survived)

# classifier.predict(df_test_features)
# result_labels = classifier.predict(df_test_features)

# ys = zip(df_test_idx,result_labels)

# write_result(ys)


dict_train_features

[{'Age': 22.0,
  'Cabin': nan,
  'Parch': 0,
  'Pclass': 3,
  'Sex': 'male',
  'SibSp': 1},
 {'Age': 38.0,
  'Cabin': 'C85',
  'Parch': 0,
  'Pclass': 1,
  'Sex': 'female',
  'SibSp': 1},
 {'Age': 26.0,
  'Cabin': nan,
  'Parch': 0,
  'Pclass': 3,
  'Sex': 'female',
  'SibSp': 0},
 {'Age': 35.0,
  'Cabin': 'C123',
  'Parch': 0,
  'Pclass': 1,
  'Sex': 'female',
  'SibSp': 1},
 {'Age': 35.0,
  'Cabin': nan,
  'Parch': 0,
  'Pclass': 3,
  'Sex': 'male',
  'SibSp': 0},
 {'Age': nan,
  'Cabin': nan,
  'Parch': 0,
  'Pclass': 3,
  'Sex': 'male',
  'SibSp': 0},
 {'Age': 54.0,
  'Cabin': 'E46',
  'Parch': 0,
  'Pclass': 1,
  'Sex': 'male',
  'SibSp': 0},
 {'Age': 2.0,
  'Cabin': nan,
  'Parch': 1,
  'Pclass': 3,
  'Sex': 'male',
  'SibSp': 3},
 {'Age': 27.0,
  'Cabin': nan,
  'Parch': 2,
  'Pclass': 3,
  'Sex': 'female',
  'SibSp': 0},
 {'Age': 14.0,
  'Cabin': nan,
  'Parch': 0,
  'Pclass': 2,
  'Sex': 'female',
  'SibSp': 1},
 {'Age': 4.0,
  'Cabin': 'G6',
  'Parch': 1,
  'Pclass': 3,
  'Se